language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- gulp
before_deploy:
- cd build
- tag=$(git tag --points-at $TRAVIS_COMMIT | tail -1)
- tar cf ../$tag.tar *
- cd ..
- if [[ -n "$(git branch --contains $TRAVIS_COMMIT | grep master)" ]]; then prerelease=false; else prerelease=true; fi
deploy:
  provider: releases
  api_key:
    secure: gSc4KspkWs9r1VV+4F9Vj6qXEAfuDFiXv/215bGz4PCObogxUb0Omi7rdUNOUbzSB7exXkYwOqyyzz57Rk47sL01GK3XOZyqZBJAkD8jAEzfyMR91KQZEYt1LYwZnvbBcAZzzxzZYumowzbu6WnT6IOEWDdTVzbMaDw4Z5WBfgVkpjs961DDcDdB8xvSg3okTX/zoHtpg5Ft//N6S3Woc9BIc/e0tRL1OnjiLmONTGI1iH1ixc+SSXasMzIlY8vrsIvxlyvZklYkPjzfCSBq/QwERW9Ql/TuaM3fR/PJPYBvAvV4LpBNOEE8+HrPkLLcp+qWXL1vxQRMEsS7GzfLUJkTOaNIs/n6Z6gHzVhIy3+f2Yf5jSw+1poMOgU/7ZNQnTKnLiWrKG1gg1ILbP+KPONF1TyVg7KH7HD7t5P5NIAAwm9FI3ThKURARR7FByGYqCPZaPtuUj55PcaAn2Xp5XKHr9VP8hIHBEyTYU7Yf7hrSYZLPvLzC/NM/Jp7VduAfudjnEcKfADVMTr4QsfKlznYjXXanoOQxV8FpMnQyga+mrdIVov6ZiTHiC3xWiFYwnaw1B/mMPJfm3PC0dh84GcU0nVahtx8Askz6FZ3Ng6un+cLQAg3wuxsGFpnlXqljUYeL5eERVUk4apNxMFGHiGcCvOmwEzpvDbj1muzbuU=
  file: $tag.tar
  skip_cleanup: true
  on:
    tags: true
  prerelease: $prerelease
